const assert = require('node:assert/strict');
const fs = require('node:fs');
const api = fs.readFileSync(require.resolve('../api/editorial/drafts'), 'utf8');
const page = fs.readFileSync(require.resolve('../docs/coanews-draft.html'), 'utf8');
const schema = fs.readFileSync(require.resolve('../docs/coanews-draft.schema.json'), 'utf8');
const migration = fs.readFileSync(require.resolve('../supabase/migrations/20260713_editorial_workflow.sql'), 'utf8');
assert.match(api, /prepareArticleDraft/);
assert.match(api, /mapPlatformCategory/);
assert.match(api, /validateBriefForPreparation/);
assert.match(api, /validateArticleDraft/);
assert.match(api, /pending_editor_approval/);
assert.match(api, /action === 'approve'/);
assert.match(api, /action === 'reject'/);
assert.match(api, /반려 사유를 편집 메모에 입력하세요/);
assert.match(api, /허용되지 않은 상태 전환/);
assert.match(page, /초안 저장/);
assert.match(page, /검토 요청/);
assert.match(page, /등록용 승인/);
assert.match(page, /approved_for_registration/);
assert.match(page, /CoaAuth\.request/);
assert.match(page, /CoaAuth\.requireSession/);
assert.doesNotMatch(page, /CRON_SECRET/);
assert.match(schema, /approved_for_registration/);
assert.match(schema, /coanews-draft\/2\.0/);
assert.match(migration, /create table if not exists editorial_drafts/);
process.stdout.write('Editorial workflow checks passed.\n');
