const assert = require('node:assert/strict');
const fs = require('node:fs');

const api = fs.readFileSync(require.resolve('../api/editorial/drafts'), 'utf8');
const page = fs.readFileSync(require.resolve('../docs/research-briefs.html'), 'utf8');
const migration = fs.readFileSync(require.resolve('../supabase/migrations/20260728_optimize_research_briefs.sql'), 'utf8');

assert.match(api, /assertCronAuth/);
assert.match(api, /view === 'briefs'/);
assert.match(api, /view === 'brief'/);
assert.match(api, /editorial_state/);
assert.match(api, /independent_source_count/);
assert.match(api, /prepared_draft_id/);
assert.match(api, /start_review/);
assert.match(api, /from: \['unreviewed', 'reviewing'\]/);
assert.match(api, /status\(409\)/);
assert.match(api, /validateBriefForPreparation/);
assert.match(api, /evaluateBriefPolicy/);
assert.match(api, /buildBriefDigest/);
assert.match(api, /validation\.can_prepare/);
assert.match(api, /action === 'prepare'/);
assert.match(api, /ai_verify_brief/);
assert.match(api, /generateBriefSummaryReview/);
assert.match(api, /fetchBriefClusters/);
assert.match(api, /isMissingBriefMetadata/);

assert.match(page, /오늘 할 일/);
assert.match(page, /브리프 선별 큐/);
assert.match(page, /지금 작성 가능/);
assert.match(page, /\/vps-collector/);
assert.match(page, /바로 기사 작성/);
assert.match(page, /요약 AI 검증/);
assert.match(page, /ai_verify_brief/);
assert.match(page, /바로 작성/);
assert.match(page, /class="blurb"/);
assert.match(page, /작성 보류/);
assert.match(page, /검증 후 기사 초안 준비/);
assert.match(page, /검토 조건으로 기사 초안 준비/);
assert.match(page, /독립 발행처/);
assert.match(page, /digest\.summary/);
assert.match(page, /digestTable/);
assert.match(page, /unreviewed', 'reviewing'/);
assert.doesNotMatch(page, /function editorialLabel/);
assert.match(page, /view=brief&id=/);
assert.match(page, /CoaAuth\.request/);
assert.match(page, /editorialState/);
assert.doesNotMatch(page, /소재 초안/);
assert.doesNotMatch(page, /editorial-drafts/);
assert.doesNotMatch(page, /CRON_SECRET/);
assert.match(page, /검토 후 기사 준비 가능/);
assert.match(migration, /editorial_state/);
assert.match(migration, /independent_source_count/);
assert.match(migration, /prepared_draft_id/);

process.stdout.write('Research briefs checks passed.\n');
