const assert = require('node:assert/strict');
const fs = require('node:fs');

const source = fs.readFileSync(require.resolve('../scripts/agent-reach-runner'), 'utf8');
const workflow = JSON.parse(fs.readFileSync(require.resolve('../n8n/workflow_agent_reach_collect.json'), 'utf8'));
assert.match(source, /body\?\.async === true/);
assert.match(source, /accepted: true/);
assert.match(source, /\.finally\(\(\) => \{ activeRun = null; \}\)/);
assert.match(source, /notifyCollectionResult/);
assert.match(source, /Collection notification skipped/);
assert.match(source, /isDryRun/);
assert.match(source, /'reddit-results'/);
assert.match(source, /completedAt: new Date\(\)\.toISOString\(\)/);
const prepareNode = workflow.nodes.find((node) => node.id === 'prepare-runner');
const callNode = workflow.nodes.find((node) => node.id === 'call-runner');
const summaryNode = workflow.nodes.find((node) => node.id === 'format-summary');
assert.match(prepareNode.parameters.jsCode, /request\s*}/);
assert.match(prepareNode.parameters.jsCode, /AGENT_REACH_LIMIT_KEYWORDS \|\| 54/);
assert.match(prepareNode.parameters.jsCode, /AGENT_REACH_OFFICIAL_RESULTS \|\| 3/);
assert.match(prepareNode.parameters.jsCode, /AGENT_REACH_RSS_RESULTS \|\| 8/);
assert.match(prepareNode.parameters.jsCode, /collection_schedules/);
assert.match(prepareNode.parameters.jsCode, /daily_time/);
assert.equal(workflow.nodes.find((node) => node.id === 'cron-trigger').parameters.rule.interval[0].minutesInterval, 5);
assert.match(callNode.parameters.jsonBody, /async: true/);
assert.match(callNode.parameters.jsonBody, /\.\.\.\$json\.request/);
assert.ok(callNode.parameters.jsonBody.indexOf('...$json.request') < callNode.parameters.jsonBody.indexOf('async: true'));
assert.match(summaryNode.parameters.jsCode, /accepted/);
process.stdout.write('Agent Reach async runner checks passed.\n');
